#!/usr/bin/env bash
# =============================================================================
# run_all.sh — regenerate everything, in order.
#   bash scripts/run_all.sh              # figures only (default)
#   bash scripts/run_all.sh --all        # physiology pipeline, then figures
#
# Stage numbering (see README.md):
#   00     package check (00_check_packages.R --install to fix)
#   01-16  physiology: oxygen model fits, Bayesian thermal/dose models
#   20-32  RNA-seq: quantification, DE, enrichment (needs reads + reference)
#   39-49  AOX inhibitor experiments (SHAM/nPG dose response, azide respirometry,
#          incubator-noise sensitivity, prothioconazole x SHAM factorial)
#   50-76  figures — every one of them generated by R
#
# Requires R (ggplot2, patchwork, dplyr, tidyr, ggrepel, scales, minpack.lm;
# brms + posterior for the physiology stage).
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
mkdir -p figures

echo "== checking R packages =="
Rscript scripts/00_check_packages.R | tail -4

if [[ "${1:-}" == "--all" ]]; then
  echo "== physiology pipeline (01-08) =="
  Rscript scripts/run_all.R
  echo "== AOX inhibitor experiments (39-47) =="
  Rscript scripts/39_aox_prepare.R .
  Rscript scripts/41_sham_rates.R . sham
  Rscript scripts/41_sham_rates.R . npg
  Rscript scripts/42_uniform_window_analysis.R .
  Rscript scripts/43_azide_rates.R .
  Rscript scripts/44_sham_denoise_sensitivity.R .
  Rscript scripts/45_ptc_sham_prepare.R .
  Rscript scripts/46_ptc_sham_prepared_traces.R .
  Rscript scripts/47_ptc_sham_rates.R .
fi

echo "== main figures =="
Rscript scripts/make_main_figures.R
echo "== supplementary figures =="
Rscript scripts/make_supp_figures.R

echo
echo "Done. 6 main + 20 supplementary figures in $ROOT/figures"
