#!/usr/bin/env bash
# =============================================================================
# run_all.sh — regenerate everything, in order.
#   bash scripts/run_all.sh              # figures only (default)
#   bash scripts/run_all.sh --all        # physiology pipeline, then figures
#
# Stage numbering (see README.md):
#   00-16  physiology: oxygen model fits, Bayesian thermal/dose models
#   20-32  RNA-seq: quantification, DE, enrichment (needs reads + reference)
#   40-41  AOX inhibitor experiment
#   50-70  figures — every one of them generated by R
#
# Requires R (ggplot2, patchwork, dplyr, tidyr, ggrepel, scales, minpack.lm;
# brms + posterior for the physiology stage).
# =============================================================================
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
mkdir -p figures

if [[ "${1:-}" == "--all" ]]; then
  echo "== physiology pipeline (01-08) =="
  Rscript scripts/run_all.R
  echo "== AOX inhibitor rates (41) =="
  Rscript scripts/41_sham_rates.R .
fi

echo "== main figures =="
Rscript scripts/make_main_figures.R
echo "== supplementary figures =="
Rscript scripts/make_supp_figures.R

echo
echo "Done. 6 main + 14 supplementary figures in $ROOT/figures"
